# Generated by Django 3.0.5 on 2020-04-09 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_book', models.ImageField(upload_to='static/static_dirs/images/')),
                ('type_book', models.CharField(max_length=250)),
                ('name_book', models.CharField(max_length=250)),
                ('amount_book', models.IntegerField()),
                ('location_book', models.CharField(max_length=250)),
                ('descri_book', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow_Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_borrowed', models.IntegerField()),
                ('status_book', models.CharField(max_length=250)),
                ('return_date', models.DateField()),
                ('date', models.DateField()),
                ('borrow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_com', models.CharField(default='SOME STRING', max_length=250)),
                ('status_com', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SOME STRING', max_length=250)),
                ('address', models.CharField(default='SOME STRING', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_room', models.CharField(default='SOME STRING', max_length=255)),
                ('status_room', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CalculateFines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('chrage', models.IntegerField()),
                ('borrow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Borrow_Notes')),
                ('librarian_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Borrower_Tutor_Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('borrow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tutor_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Tutor_room')),
            ],
        ),
        migrations.CreateModel(
            name='Borrower_Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('borrow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Computer')),
            ],
        ),
        migrations.CreateModel(
            name='Borrow_Book_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_info_id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Book_info')),
                ('borrow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Borrow_Notes')),
            ],
        ),
        migrations.AddField(
            model_name='book_info',
            name='published_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Publisher'),
        ),
    ]
