# Generated by Django 3.0.5 on 2020-04-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor_room',
            name='name_room',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
    ]
