# Generated by Django 3.0.5 on 2020-04-10 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mylibrary', '0003_auto_20200410_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow_Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_isbn', models.CharField(default='SOME STRING', max_length=250)),
                ('date', models.DateField()),
                ('return_date', models.DateField()),
                ('borrow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book_info',
            name='isbn',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
        migrations.CreateModel(
            name='CalculateFines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('chrage', models.IntegerField()),
                ('borrow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Borrow_Notes')),
                ('librarian_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow_Book_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_info_id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Book_info')),
                ('borrow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Borrow_Notes')),
            ],
        ),
    ]
