# Generated by Django 3.0.5 on 2020-04-10 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0006_auto_20200410_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_notes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 22, 10, 18, 129931)),
        ),
    ]
