# Generated by Django 3.0.5 on 2020-04-11 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0008_auto_20200410_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_info',
            name='type_book',
        ),
        migrations.AlterField(
            model_name='borrow_notes',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 17, 48, 55, 10850)),
        ),
        migrations.DeleteModel(
            name='Borrow_Book_Info',
        ),
    ]
