# Generated by Django 3.0.5 on 2020-04-11 10:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0010_auto_20200411_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_type_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Book_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(default='SOME STRING', max_length=250)),
                ('img_book', models.ImageField(upload_to='static/static_dirs/images/')),
                ('name_book', models.CharField(max_length=250)),
                ('amount_book', models.IntegerField()),
                ('location_book', models.CharField(max_length=250)),
                ('descri_book', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='borrow_notes',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 17, 53, 22, 3584)),
        ),
        migrations.CreateModel(
            name='Borrow_Book_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_info_id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Book_info')),
                ('borrow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Borrow_Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Book_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_book', models.CharField(default='SOME STRING', max_length=250)),
                ('all_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mylibrary.All_type')),
            ],
        ),
        migrations.AddField(
            model_name='book_info',
            name='book_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mylibrary.Book_type'),
        ),
        migrations.AddField(
            model_name='book_info',
            name='published_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Publisher'),
        ),
    ]
