# Generated by Django 3.0.5 on 2020-04-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0012_auto_20200411_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower_computer',
            name='time',
        ),
        migrations.RemoveField(
            model_name='borrower_tutor_room',
            name='time',
        ),
        migrations.AlterField(
            model_name='borrow_notes',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='borrow_notes',
            name='return_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='borrower_computer',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='borrower_tutor_room',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='calculatefines',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
