# Generated by Django 3.0.3 on 2020-04-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0013_auto_20200411_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower_tutor_room',
            name='borrow_user',
        ),
        migrations.RemoveField(
            model_name='borrower_tutor_room',
            name='tutor_room',
        ),
        migrations.DeleteModel(
            name='Borrower_Computer',
        ),
        migrations.DeleteModel(
            name='Borrower_Tutor_Room',
        ),
        migrations.DeleteModel(
            name='Computer',
        ),
        migrations.DeleteModel(
            name='Tutor_room',
        ),
    ]
