# Generated by Django 3.0.3 on 2020-04-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0015_borrower_computer_borrower_tutor_room_computer_tutor_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrower_Tutor_Room',
        ),
        migrations.DeleteModel(
            name='Tutor_room',
        ),
    ]
