# Generated by Django 3.0.3 on 2020-04-12 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mylibrary', '0016_auto_20200412_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_room', models.CharField(default='SOME STRING', max_length=250)),
                ('img_tutor', models.ImageField(upload_to='static/static_dirs/images/tutor/')),
                ('status_room', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('UNAVAILABLE', 'UNAVAILABLE')], default='AVAILABLE', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Borrower_Tutor_Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('borrow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tutor_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Tutor_room')),
            ],
        ),
    ]
