# Generated by Django 3.0.5 on 2020-04-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0017_borrower_tutor_room_tutor_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatefines',
            name='borrow_user',
        ),
        migrations.RemoveField(
            model_name='calculatefines',
            name='librarian_id',
        ),
        migrations.DeleteModel(
            name='Borrow_Book_Info',
        ),
        migrations.DeleteModel(
            name='CalculateFines',
        ),
    ]
