# Generated by Django 3.0.5 on 2020-04-14 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mylibrary', '0018_auto_20200414_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculateFines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('chrage', models.IntegerField()),
                ('borrow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Borrow_Notes')),
                ('librarian_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow_Book_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_info_id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Book_info')),
                ('borrow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Borrow_Notes')),
            ],
        ),
    ]
