# Generated by Django 3.0.5 on 2020-04-14 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mylibrary', '0019_borrow_book_info_calculatefines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_book_info',
            name='borrow_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
