# Generated by Django 3.0.5 on 2020-04-15 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0021_idcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Idcard',
        ),
    ]
