# Generated by Django 3.0.5 on 2020-04-15 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('mylibrary', '0022_delete_idcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idcard',
            fields=[
                ('user_idcard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('idcard', models.IntegerField()),
            ],
        ),
    ]
