# Generated by Django 3.0.5 on 2020-04-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0023_idcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='idcard',
            field=models.CharField(max_length=250),
        ),
    ]
