# Generated by Django 3.0.5 on 2020-04-15 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0024_auto_20200415_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_notes',
            name='book_isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mylibrary.Book_info'),
        ),
    ]
