# Generated by Django 3.0.5 on 2020-04-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0026_remove_calculatefines_chrage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculatefines',
            old_name='librarian_id',
            new_name='user_id',
        ),
    ]
