# Generated by Django 3.0.5 on 2020-04-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0027_auto_20200415_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_notes',
            name='charg',
            field=models.IntegerField(default='1'),
        ),
    ]
