# Generated by Django 3.0.5 on 2020-04-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0029_auto_20200415_2331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrow_Book_Info',
        ),
    ]
