# Generated by Django 3.0.5 on 2020-04-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0030_delete_borrow_book_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatefines',
            name='status_cal',
            field=models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('UNCOMPLETE', 'UNCOMPLETE')], default='UNCOMPLETE', max_length=12),
        ),
    ]
