# Generated by Django 3.0.5 on 2020-04-18 15:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mylibrary', '0032_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='img_url',
            new_name='img_profile',
        ),
    ]
