# Generated by Django 3.0.5 on 2020-04-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0033_auto_20200418_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcard',
            name='img_profile',
            field=models.ImageField(default="{% static 'user.png' %}", upload_to='static/static_dirs/images/profile/'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
