# Generated by Django 3.0.5 on 2020-04-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0036_auto_20200419_2143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
