# Generated by Django 3.0.5 on 2020-04-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0037_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='img_profile',
            field=models.ImageField(default='user.png', upload_to='media/static/static_dirs/images/profile/'),
        ),
    ]
