# Generated by Django 3.0.5 on 2020-04-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0038_auto_20200419_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='img_profile',
            field=models.ImageField(upload_to='static/static_dirs/images/profile/'),
        ),
    ]
