# Generated by Django 3.0.5 on 2020-04-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0039_auto_20200419_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idcard',
            name='img_profile',
        ),
    ]
