# Generated by Django 3.0.5 on 2020-04-20 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0041_auto_20200420_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower_computer',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 23, 57, 44, 854275)),
        ),
        migrations.AlterField(
            model_name='borrower_computer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 22, 57, 44, 854275)),
        ),
    ]
