# Generated by Django 3.0.5 on 2020-04-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0043_auto_20200420_2321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrower_Computer',
        ),
    ]
