# Generated by Django 3.0.5 on 2020-04-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0046_auto_20200422_1818'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrower_Computer',
        ),
    ]
