# Generated by Django 3.0.5 on 2020-04-22 12:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mylibrary', '0047_delete_borrower_computer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower_Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 4, 22, 19, 2, 50, 949393))),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2020, 4, 22, 19, 3, 50, 949393))),
                ('borrow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Computer')),
            ],
        ),
    ]
