# Generated by Django 3.0.5 on 2020-04-22 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0048_borrower_computer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower_computer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 22, 42, 31, 153891)),
        ),
        migrations.AlterField(
            model_name='borrower_computer',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 22, 57, 31, 153891)),
        ),
    ]
